# Generated by Django 2.1.7 on 2019-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('authorized', models.BooleanField(default=False, verbose_name='Authorized')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
    ]
